source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Crazysiri/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'UBLib_Example' do
  pod 'UBLib', :path => '../'
  target 'UBLib_Tests' do
    inherit! :search_paths

    
  end
end

