source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/ppz_bj/LTCaptureKit.git'

use_frameworks!

platform :ios, '8.0'

target 'UBLib_Example' do
  pod 'UBLib', :path => '../'

  target 'UBLib_Tests' do
    inherit! :search_paths

    
  end
end
